Repository amanjha8100/chords, pull requests merged in 2021-10, with the labels that each got.

#1 New Updates
  .env.sample
  .gitignore
  app.py
  music.py
  requirements.txt
Labels: hacktoberfest-accepted

#2 Added more info to the messages
  music.py
Labels: hacktoberfest-accepted

#3 Skipping two songs at a time, bug fix!
  music.py
Labels: hacktoberfest-accepted

#4 Role fix for leave command || Music bot leave command
  music.py
Labels: hacktoberfest-accepted

#5 Added README.md
  README.md
  app.py
Labels: hacktoberfest-accepted

#14 PR associated with issue#13.
  LICENSE
Labels: hacktoberfest-accepted, hacktoberfest

#18 Playnext Feature
  app.py
  music.py
Labels: hacktoberfest-accepted, hacktoberfest, feature

#19 Remove a song from queue feature added.
  music.py
Labels: hacktoberfest-accepted, hacktoberfest, feature

#21 Added new commands playnext and remove to the docs
  README.md
  doc/deploy.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest
